const SPORT_CRICKET = "4"
const SPORT_TENNIS = "2"
const SPORT_SOCCER = "1"
const CRICKET_LIVE_SET_MIN = 20
const SOCCER_LIVE_SET_MIN = 3
const TENNIS_LIVE_SET_MIN = 3

module.exports = {
  SPORT_CRICKET, SPORT_TENNIS, SPORT_SOCCER, CRICKET_LIVE_SET_MIN, SOCCER_LIVE_SET_MIN, TENNIS_LIVE_SET_MIN
}
